version: "3"
services:
  lavagna:
    image: digitalfondue/lavagna:stable
    environment:
      - DB_DIALECT=MYSQL
      - DB_URL=jdbc:mysql://db:3306/lavagna?useUnicode=true&characterEncoding=utf-8
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - default
      - office
    links:
      - db
    external_links:
      - openldap
    depends_on:
      - db
  db:
    image: library/mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lavagna
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - default
    volumes:
      - lavagna-db:/var/lib/mysql

volumes:
  lavagna-db:
networks:
  default:
    driver: bridge
  office:
    external: true
